version: 1.3.0.{build}
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '1.3.0'
  package_version: '1.3.0'
image: Visual Studio 2017
configuration:
- Release
before_build:
- ps: >-
    choco install opencover.portable --no-progress

    choco install codecov --no-progress

    nuget restore
build:
  project: ZaifApiWrapper.sln
  verbosity: minimal
  publish_nuget: true
test_script:
- ps: >-
    $ErrorActionPreference = 'Stop'

    OpenCover.Console.exe -register:user -target:'dotnet.exe' -targetargs:"test $($PWD)\ZaifApiWrapper.Test\ZaifApiWrapper.Test.csproj --no-build" -filter:'+[ZaifApiWrapper*]* -[ZaifApiWrapper.Test*]*' -output:"$($PWD)\coverage.xml" -oldStyle

    codecov.exe -f "$($PWD)\coverage.xml" -t '32a9b2e4-a2b8-432e-8aab-29d12ad21d2f'
deploy:
- provider: NuGet
  api_key:
    secure: IDd30vnNAoQxzZjLeBllmb5kTntAlMiNNrfbYf0Vl4BU7npAh0nomnug13hdWgAH
  artifact: NuGet package
  on:
    appveyor_repo_tag: true
    branch: /master/