version: ci-{branch}-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration:
- Debug
- Release
before_build:
- ps: >-
    choco install opencover.portable --no-progress

    choco install codecov --no-progress

    nuget restore src/Zaif.sln
build:
  project: src/Zaif.sln
  verbosity: minimal
test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\src\ZaifApiWrapper.Test\bin\%CONFIGURATION%\netstandard2.0\ZaifApiWrapper.dll -noshadow" -filter:"+[ZaifApiWrapper*]* -[ZaifApiWrapper.Test*]*" -output:".\coverage.xml"
after_test:
- ps: >-
    codecov.exe -f '.\coverage.xml' -t '32a9b2e4-a2b8-432e-8aab-29d12ad21d2f'
artifacts:
- path: '**/Release/*.nupkg'
  name: NuGet Package
deploy:
- provider: NuGet
  api_key:
    secure: IDd30vnNAoQxzZjLeBllmb5kTntAlMiNNrfbYf0Vl4BU7npAh0nomnug13hdWgAH
  artifact: NuGet Package
  on:
    branch: /Release/\.[1-9]\.[0-9]\.[0-9]/